version: "3.8"

services:
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server-siswa1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - PASSWORD=siswa1pass
    volumes:
      - ./code-server-data:/config
      - ./project:/config/workspace
    ports:
      - "8081:8443" # akses editor: https://yourdomain.com:8081

  php-fpm:
    image: php:8.2-fpm
    container_name: php-fpm-siswa1
    volumes:
      - ./project:/var/www/html

  nginx:
    image: nginx:latest
    container_name: nginx-siswa1
    depends_on:
      - php-fpm
    volumes:
      - ./project:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:80" # akses subdomain siswa: http://siswa1.domain.com
